### ISSUE TITLE
IOS .framework dependencies not found when upgrading AIR SDK

### ISSUE THREAD

**Issue by syberkitten** [myflashlab/common-dependencies-ANE#9]
since upgrading Air SDK to 26,
getting this compiler error:

ld: framework not found FirebaseAuth
ld: framework not found FirebaseAuth
Compilation failed while executing : ld64

Where should the IOS dependencies be copied to?

Using the latest dependencies from here:
https://github.com/myflashlab/Firebase-ANE/blob/master/Dependencies.md

It cannot be that such a common task is only documented here:
https://github.com/myflashlab/Firebase-ANE/wiki/A.3.-Add-the-SDK

Stating that:

> Note3: Dependency Frameworks for the iOS side, must be copied to your AdobeAir SDK to the following path: "yourAirSDK\lib\aot\stub" 

So let me Re-cap:

Every time the AIR SDK version is upgraded the .framework files from the downloaded
IOS SDK: https://dl.google.com/firebase/sdk/ios/4_0_1/Firebase-4.0.1.zip
 
Need be copied to:
yourAirSDK\lib\aot\stub

For the **FireBaseAuth.ane** 
these are the .framework files:

FirebaseAuth.framework
FirebaseAnalytics.framework
FirebaseCore.framework (core is need at any case)
FirebaseInstanceID.framework

**But, now I got this error:**
ld: framework not found GTMSessionFetcher
ld: framework not found GTMSessionFetcher
Compilation failed while executing : ld64

**was missing:**
GTMSessionFetcher.framework

**and now getting this:**
ld: framework not found GoogleToolboxForMac
ld: framework not found GoogleToolboxForMac
Compilation failed while executing : ld64

**fixed when copying:**
GoogleToolboxForMac.framework

**and now I'm getting this huge error:**
Undefined symbols for architecture arm64:
  "_nano_encode_repeated_string", referenced from:
      _firapb_set_string_filter_encoders in FirebaseAnalytics(firapb_string_filter_encoder_f42092f1ba2fa9d559b019faba84cc6a.o)
  "_nano_encode_repeated_uint64", referenced from:
      _firapb_set_result_data_encoders in FirebaseAnalytics(firapb_result_data_encoder_373a816d02f878f3857bb6d0ba8021a2.o)
  "_nano_encode_string", referenced from:
      _firapb_set_event_encoders in

**Comment by syberkitten** [comment]
**the above nasty error solved by re-copying the .framework files
so these in total (6):**

FirebaseAuth.framework
FirebaseAnalytics.framework
FirebaseCore.framework 
FirebaseInstanceID.framework
GoogleToolboxForMac.framework
GTMSessionFetcher.framework

**Comment by myflashlab** [comment]
Although you closed the issue but I really need to emphasize on the fact that you need to be very careful about which Firebase SDK you are downloading: The latest Firebase ANE is V4.0.0 and as described [here](https://github.com/myflashlab/Firebase-ANE/blob/master/Dependencies.md#v400) you will need to use Firebase V3.13.0 https://dl.google.com/firebase/sdk/ios/3_13_0/Firebase-3.13.0.zip

This is very important. Please do not use newer versions unless we officially support them. Doing that might cause unexpected error messages. Wait for us to release new versions.
